Update wesnoth-ala.po
cooljeanius/A_Little_Adventure pull request #12
Opened 2022-02-25 21:19 UTC by MultiSeptim

next run @celerini

2022-02-26 08:27 UTC, celerini requested changes

2022-02-26 08:27 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"znich postavila valy."
```suggestion
"z nich postavila valy."
```

2022-02-26 08:27 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"Hej, jediní, kdo se tu chová jako zvěř jste vy, wesnoťani! Tohle je Fangy, "
```suggestion
"Hej, jediní, kdo se tu chová jako zvěř, jste vy, wesnoťani! Tohle je Fangy, "
```

2022-02-26 08:27 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"Hm, ach! Protože jste se sem přišli se vypořádat s Gruntem, budu vám muset "
```suggestion
"Hm, ach! Protože jste se sem přišli vypořádat s Gruntem, budu vám muset "
```

2022-02-26 08:27 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"zvířata pro svoje gobliny. A protože zápaďáci z města jako vy toho o těhle "
```suggestion
"zvířata pro svoje gobliny. A protože zápaďáci z města jako vy toho o těchhle "
```

2022-02-26 08:27 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"Slyšela jsi, miláčku? Tenhle wesnothský klacek nakonec není takový brutián! "
a [new word](https://www.google.com/search?q=site%3Acz+bruti%C3%A1n)?

2022-02-26 08:27 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"Glubtrub nemít rád hady! Málo tuku k jídlu a ne moc dobré! Chtít zabít naše "
```suggestion
"Glubtrub nemít rád hady! Málo tuku k jídlu, a ne moc dobré! Chtít zabít naše "
```

2022-03-02 21:51 UTC, MultiSeptim commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"Slyšela jsi, miláčku? Tenhle wesnothský klacek nakonec není takový brutián! "
Hrubián samozřejmě.

2022-03-03 06:46 UTC, MultiSeptim commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"Slyšela jsi, miláčku? Tenhle wesnothský klacek nakonec není takový brutián! "
A navrhni tam prosím Slyšelas.

2022-03-03 22:07 UTC, celerini requested changes

2022-03-03 22:07 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"Slyšela jsi, miláčku? Tenhle wesnothský klacek nakonec není takový brutián! "
```suggestion
"Slyšelas, miláčku? Tenhle wesnothský klacek nakonec není takový hrubián! "
```

2022-03-04 15:32 UTC, MultiSeptim commented
Ready to merge.

2022-03-04 18:10 UTC, merged