Update wesnoth-ala.po
cooljeanius/A_Little_Adventure pull request #15
Opened 2022-03-07 22:50 UTC by MultiSeptim

Next run @celerini

2022-03-08 19:51 UTC, celerini requested changes

2022-03-08 19:51 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +msgstr "Podívejte k severu, přátele, ti velcí zelení hadi jsou jedovatí!"
```suggestion
msgstr "Podívejte k severu, přátelé, ti velcí zelení hadi jsou jedovatí!"
```

2022-03-08 19:51 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"nějací skřetí náčelníci nerozhodnou usadit se na Gruntovo území, nebo dokud "
```suggestion
"nějací skřetí náčelníci nerozhodnou usadit se na Gruntovo území nebo dokud "
```

2022-03-08 19:51 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"zaručovaly bezpečnost hranic a žádná loď nemohla plout ani proti ani po "
```suggestion
"zaručovaly bezpečnost hranic a žádná loď nemohla plout ani proti, ani po "
```

2022-03-08 19:51 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"předpokládat, že jejich stav dobrý nebude. Zkrátka obnovení karavanní stezky "
trying to avoid repeating words
```suggestion
"předpokládat, že dobrý nebude. Zkrátka obnovení karavanní stezky "
```

2022-03-08 19:51 UTC, celerini commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +"osadníky ze západu, lidi, obdařené odvahou a duchem iniciativy, vlastnostmi, "
```suggestion
"osadníky ze západu, lidi obdařené odvahou a duchem iniciativy, vlastnostmi, "
```

2022-03-08 20:02 UTC, MultiSeptim commented
Ready to merge.
I'm going to be a little quiet now, because I'm too busy now. So it is possible to use this time gap for changes you need, cooljeanius.

2022-03-09 00:11 UTC, merged

2022-03-09 00:12 UTC, cooljeanius commented
> Ready to merge. I'm going to be a little quiet now, because I'm too busy now. So it is possible to use this time gap for changes you need, cooljeanius.

OK thanks; I'm going to make a new release in a bit...

2022-03-09 00:32 UTC, cooljeanius commented
ok, the new release, 4.1.3, is now on the 1.16 add-on server! Corresponding tag is here: https://github.com/cooljeanius/A_Little_Adventure/releases/tag/4.1.3