add authors, unify nereids, fix word order
cooljeanius/A_Little_Adventure pull request #27
Opened 2022-04-28 18:56 UTC by celerini

@MultiSeptim, please check this.

Eric, please wait until @MultiSeptim approve or reject my changes.

2022-04-28 20:44 UTC, MultiSeptim requested changes

2022-04-28 20:44 UTC, MultiSeptim commented on translations/cs/LC_MESSAGES/wesnoth-ala.po
> +# Septim, 2022
```suggestion
# Petr Šlejhar (Septim), 2022
```

2022-04-28 20:45 UTC, MultiSeptim commented
Jinak OK.

2022-04-30 07:44 UTC, celerini commented
Eric, you can merge it. Thanks.

2022-04-30 16:09 UTC, merged

2022-04-30 16:09 UTC, cooljeanius commented
> Eric, you can merge it. Thanks.

OK, merged!